import type { Project, Task } from "./types";

const now = new Date().toISOString();

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p-001",
    name: "Website Redesign",
    description: "Complete overhaul of the marketing site",
    color: "#6366F1",
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p-002",
    name: "Mobile App v2",
    description: "Native iOS and Android rebuild",
    color: "#EC4899",
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p-003",
    name: "API Platform",
    description: "Developer API and documentation",
    color: "#22C55E",
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t-001",
    projectId: "p-001",
    title: "Define information architecture",
    description: "Map out full sitemap and user flows for the redesign",
    status: "done",
    priority: "high",
    assignee: { name: "Ken Stanley", initials: "KS", color: "#6366F1" },
    tags: ["planning", "ux"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-002",
    projectId: "p-001",
    title: "Design system components",
    description: "Build reusable component library - buttons, cards, inputs, modals",
    status: "in_progress",
    priority: "high",
    assignee: { name: "Ken Stanley", initials: "KS", color: "#6366F1" },
    tags: ["design", "ui"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-003",
    projectId: "p-001",
    title: "Hero section prototype",
    description: "Interactive hero with scroll-triggered animations",
    status: "in_progress",
    priority: "medium",
    assignee: { name: "TARS", initials: "TA", color: "#8B5CF6" },
    tags: ["frontend", "animation"],
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-004",
    projectId: "p-001",
    title: "SEO audit and meta tags",
    description: "Analyze current SEO performance and set up proper meta structure",
    status: "backlog",
    priority: "medium",
    tags: ["seo"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-005",
    projectId: "p-001",
    title: "Contact form with validation",
    description: "Multi-step form with Zod validation and email integration",
    status: "todo",
    priority: "medium",
    assignee: { name: "TARS", initials: "TA", color: "#8B5CF6" },
    tags: ["frontend", "backend"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-006",
    projectId: "p-001",
    title: "Performance optimization pass",
    description: "Lighthouse score >95, image optimization, lazy loading",
    status: "backlog",
    priority: "low",
    tags: ["performance"],
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-007",
    projectId: "p-001",
    title: "Launch checklist",
    description: "DNS, SSL, redirects, analytics, error tracking",
    status: "todo",
    priority: "high",
    tags: ["devops", "launch"],
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-008",
    projectId: "p-002",
    title: "Set up React Native project",
    description: "Expo managed workflow with TypeScript template",
    status: "done",
    priority: "high",
    assignee: { name: "Ken Stanley", initials: "KS", color: "#6366F1" },
    tags: ["setup"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-009",
    projectId: "p-002",
    title: "Authentication flow",
    description: "Sign up, login, forgot password, biometric auth",
    status: "in_progress",
    priority: "urgent",
    assignee: { name: "Ken Stanley", initials: "KS", color: "#6366F1" },
    tags: ["auth", "security"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-010",
    projectId: "p-002",
    title: "Push notification service",
    description: "FCM + APNs integration with notification preferences",
    status: "backlog",
    priority: "medium",
    tags: ["backend", "mobile"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-011",
    projectId: "p-003",
    title: "OpenAPI spec v1",
    description: "Define all endpoints, request/response schemas, auth",
    status: "todo",
    priority: "high",
    assignee: { name: "TARS", initials: "TA", color: "#8B5CF6" },
    tags: ["api", "docs"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-012",
    projectId: "p-003",
    title: "Rate limiting middleware",
    status: "backlog",
    priority: "medium",
    tags: ["backend", "security"],
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
];
